/**
 * GENERATED by `npm run gen:api` from web/openapi.json.
 * Do not edit by hand. Regenerate it after a backend contract change
 * (see "Regenerating API types" in the README).
 */

export interface paths {
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Channels */
        post: operations["post_channels_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Channel Backfill
         * @description Backfill a registered channel's newest ``limit`` uploads (#41, D9b).
         *
         *     This is the one API route that runs a subprocess: the catalog is a
         *     yt-dlp flat listing, bounded by ``deps.BACKFILL_LIST_TIMEOUT_SEC`` and
         *     ``MAX_BACKFILL_LIMIT``. It departs from "the API performs no processing"
         *     because architecture.md 8.3 wants a synchronous dry-run answer, and a
         *     flat listing is network-bound, not CPU work (owner decision; moving it
         *     to a worker is #115). A dry run (the default) writes nothing; a real run
         *     answers 202 when it enqueued at least one job, else 200.
         */
        post: operations["post_channel_backfill_channels__channel_id__backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness plus queue depth by kind and state; 503 when the database is not usable.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Jobs
         * @description A page of ``jobs``, newest first (#44). ``payload`` is never exposed.
         */
        get: operations["get_ops_jobs_ops_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ops Job Retry
         * @description Revive one ``dead`` job in place: same id, ``attempts`` reset to 0 (#44).
         *
         *     One conditional ``UPDATE`` (``PostgresQueue.retry_dead``) decides and
         *     writes the new state together, so a concurrent change can only ever be
         *     caught, never missed. The one log line, ``ops.job_retried``, is emitted
         *     only on success; a refusal writes nothing and leaves no trace beyond the
         *     response.
         */
        post: operations["post_ops_job_retry_ops_jobs__id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search
         * @description Videos whose preferred transcript matches ``q``, most relevant first.
         *
         *     The body never echoes ``q``, and the log line records only its length.
         *     Any database error is a 503 (``deps.get_read_conn``).
         */
        get: operations["get_search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Videos
         * @description The library, newest published first; ``total`` counts every match.
         */
        get: operations["get_videos_videos_get"];
        put?: never;
        /** Post Videos */
        post: operations["post_videos_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Detail
         * @description One video, its status, best transcript (D2) and latest analysis.
         */
        get: operations["get_video_detail_videos__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Analyses
         * @description Every analysis run of the video, newest first (D7).
         */
        get: operations["get_video_analyses_videos__video_id__analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Render
         * @description The video's latest analysis as a self-contained page (D12c).
         *
         *     The page comes from ``render.render_analysis_html``; this handler only
         *     reads and sets the security headers. Neither 404 echoes the id.
         */
        get: operations["get_video_render_videos__video_id__render_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Transcript
         * @description One page of the best transcript's segments (D2, architecture.md 9).
         */
        get: operations["get_video_transcript_videos__video_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveJobOut */
        ActiveJobOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** State */
            state: string;
        };
        /** AnalysisList */
        AnalysisList: {
            /** Items */
            items: components["schemas"]["AnalysisOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Chunk Strategy */
            chunk_strategy: string;
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Cost Usd */
            cost_usd: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Id */
            id: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Quotes */
            quotes: components["schemas"]["QuoteOut"][];
            speaker_roster: components["schemas"]["JsonValue"] | null;
            /** Tldr */
            tldr: string;
            /** Topics */
            topics: components["schemas"]["TopicOut"][];
            /** Transcript Id */
            transcript_id: number;
            /** Transcript Source */
            transcript_source: string;
        };
        /** BackfillEstimate */
        BackfillEstimate: {
            /** Assumes */
            assumes: string;
            /** Audio Sec */
            audio_sec: number;
            /** Rtf */
            rtf: number | null;
            /** Rtf Samples */
            rtf_samples: number;
            /** Transcription Sec */
            transcription_sec: number | null;
            /** Unknown Duration */
            unknown_duration: number;
        };
        /** BackfillRequest */
        BackfillRequest: {
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Limit */
            limit: number;
        };
        /** BackfillResponse */
        BackfillResponse: {
            /** Already Known */
            already_known: number;
            /** Backfill Id */
            backfill_id: string | null;
            /** Channel Id */
            channel_id: string;
            /** Dry Run */
            dry_run: boolean;
            /** Enqueued */
            enqueued: number;
            estimate: components["schemas"]["BackfillEstimate"];
            /** Limit */
            limit: number;
            /** Listed */
            listed: number;
            /** New Videos */
            new_videos: number;
            /** Total Count */
            total_count: number | null;
            /** Video Ids */
            video_ids: string[];
        };
        /** ChannelRegistration */
        ChannelRegistration: {
            /** Active */
            active: boolean;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Channel Id */
            channel_id: string;
            /** Created */
            created: boolean;
            /**
             * Monitor From
             * Format: date-time
             */
            monitor_from: string;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Confidence */
            confidence: string | null;
            /** Source Chunk Seq */
            source_chunk_seq: number | null;
            /** Speaker */
            speaker: string;
            /** Start Sec */
            start_sec: number | null;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description ``GET /healthz`` 200 body: liveness plus queue depth by kind and state.
         */
        HealthOut: {
            /** Queue */
            queue: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Status */
            status: string;
        };
        /** JobListOut */
        JobListOut: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Next Before Id */
            next_before_id: number | null;
        };
        /**
         * JobOut
         * @description One ``jobs`` row for the Ops view (#44). ``payload`` is never exposed.
         */
        JobOut: {
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dedupe Key */
            dedupe_key: string;
            /** Error Class */
            error_class: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Last Error */
            last_error: string | null;
            /** Locked By */
            locked_by: string | null;
            /** Priority */
            priority: number;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /** State */
            state: string;
            /** Video Id */
            video_id: string;
            /** Video Title */
            video_title: string | null;
        };
        JsonValue: unknown;
        /** LastFailureOut */
        LastFailureOut: {
            /** Error Class */
            error_class: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: number;
            /** Kind */
            kind: string;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Source Chunk Seq */
            source_chunk_seq: number | null;
            /** Speaker */
            speaker: string;
            /** Start Sec */
            start_sec: number | null;
            /** Text */
            text: string;
        };
        /** SearchPage */
        SearchPage: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /** Channel Id */
            channel_id: string | null;
            /** Channel Title */
            channel_title: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Excerpts */
            excerpts: components["schemas"]["SpanOut"][][];
            /** Published At */
            published_at: string | null;
            /** Title */
            title: string | null;
            /** Transcript Source */
            transcript_source: string;
            /** Unavailable */
            unavailable: string | null;
            /** Video Id */
            video_id: string;
        };
        /** SegmentOut */
        SegmentOut: {
            /** End */
            end: number;
            /** Index */
            index: number;
            /** Speaker */
            speaker: string | null;
            /** Start */
            start: number;
            /** Text */
            text: string;
        };
        /** SpanOut */
        SpanOut: {
            /** Match */
            match: boolean;
            /** Text */
            text: string;
        };
        /** SubmitRef */
        SubmitRef: {
            /** Url */
            url: string;
        };
        /** TopicOut */
        TopicOut: {
            /** Seq */
            seq: number;
            /** Start Sec */
            start_sec: number | null;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** TranscriptOut */
        TranscriptOut: {
            /** Language */
            language: string | null;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Source */
            source: string;
            /** Speaker Source */
            speaker_source: string;
            /** Total Segments */
            total_segments: number;
            /** Transcript Id */
            transcript_id: number;
            /** Video Id */
            video_id: string;
        };
        /** TranscriptSummary */
        TranscriptSummary: {
            /** Id */
            id: number;
            /** Language */
            language: string | null;
            /** Segment Count */
            segment_count: number;
            /** Source */
            source: string;
            /** Speaker Source */
            speaker_source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoDetail */
        VideoDetail: {
            active_job: components["schemas"]["ActiveJobOut"] | null;
            analysis: components["schemas"]["AnalysisOut"] | null;
            /** Channel Id */
            channel_id: string | null;
            /** Channel Title */
            channel_title: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            last_failure: components["schemas"]["LastFailureOut"] | null;
            /** Latest Analysis At */
            latest_analysis_at: string | null;
            /** Origin */
            origin: string;
            /** Published At */
            published_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "processing" | "unavailable" | "failed" | "idle";
            /** Title */
            title: string | null;
            transcript: components["schemas"]["TranscriptSummary"] | null;
            /** Unavailable */
            unavailable: string | null;
            /** Video Id */
            video_id: string;
        };
        /** VideoItem */
        VideoItem: {
            active_job: components["schemas"]["ActiveJobOut"] | null;
            /** Channel Id */
            channel_id: string | null;
            /** Channel Title */
            channel_title: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            last_failure: components["schemas"]["LastFailureOut"] | null;
            /** Latest Analysis At */
            latest_analysis_at: string | null;
            /** Origin */
            origin: string;
            /** Published At */
            published_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "processing" | "unavailable" | "failed" | "idle";
            /** Title */
            title: string | null;
            /** Unavailable */
            unavailable: string | null;
            /** Video Id */
            video_id: string;
        };
        /** VideoList */
        VideoList: {
            /** Items */
            items: components["schemas"]["VideoItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** VideoSubmission */
        VideoSubmission: {
            /** Created */
            created: boolean;
            /** Job Id */
            job_id: number;
            /** State */
            state: string;
            /** Video Id */
            video_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_channels_channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRef"];
            };
        };
        responses: {
            /** @description Already registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRegistration"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRegistration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_channel_backfill_channels__channel_id__backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Dry run, or nothing new */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_ops_jobs_ops_jobs_get: {
        parameters: {
            query?: {
                state?: ("pending" | "running" | "done" | "dead") | null;
                kind?: ("analyze" | "ingest" | "transcribe") | null;
                error_class?: ("PERMANENT_SOURCE" | "TRANSIENT_NETWORK" | "RATE_LIMITED" | "TOOL_FAILURE" | "LLM_INVALID_OUTPUT" | "LLM_UNAVAILABLE" | "RESOURCE" | "BUG" | "none") | null;
                before_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ops_job_retry_ops_jobs__id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_search_get: {
        parameters: {
            query: {
                q: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_videos_videos_get: {
        parameters: {
            query?: {
                channel?: string | null;
                status?: ("done" | "processing" | "unavailable" | "failed" | "idle") | null;
                published_after?: string | null;
                published_before?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_videos_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRef"];
            };
        };
        responses: {
            /** @description Already submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSubmission"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_detail_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_analyses_videos__video_id__analyses_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_render_videos__video_id__render_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_transcript_videos__video_id__transcript_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
