// Generates src/api/schema.d.ts from openapi.json (issue #46). Reads only that
// file: no network. `--check` regenerates into a temp file and compares it with
// the committed schema.d.ts, changing nothing committed.
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const input = join(root, 'openapi.json')
const output = join(root, 'src', 'api', 'schema.d.ts')

const HEADER = `/**
 * GENERATED by \`npm run gen:api\` from web/openapi.json.
 * Do not edit by hand. Regenerate it after a backend contract change
 * (see "Regenerating API types" in the README).
 */
`

const ast = await openapiTS(pathToFileURL(input))
const generated = HEADER + '\n' + astToString(ast).replace(/\r\n/g, '\n')

if (process.argv.includes('--check')) {
  const dir = mkdtempSync(join(tmpdir(), 'gen-api-'))
  try {
    const tmp = join(dir, 'schema.d.ts')
    writeFileSync(tmp, generated, 'utf8')
    const committed = readFileSync(output, 'utf8')
    if (readFileSync(tmp, 'utf8') !== committed) {
      console.error(
        'src/api/schema.d.ts is out of date with openapi.json. Run: npm run gen:api',
      )
      process.exit(1)
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
} else {
  writeFileSync(output, generated, 'utf8')
}
